name: native_dio_adapter_desktop
description: Native Dio transports for Windows (WinHTTP) and Linux (Rust reqwest), with configurable proxies.
version: 0.1.0
repository: https://github.com/umeow0716/native_dio_adapter_desktop
environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'
platforms:
  linux:
  windows:
dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  rhttp: ^0.18.0
  win_http: ^0.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
